# -*- coding: utf-8 -*-
"""PR HGR CNN .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKxsx9_El1hjsm5rrvmQ518_UbFSpSpS
"""

import os
import zipfile
from google.colab import drive
drive.mount('/content/drive')

import os
import zipfile
from google.colab import drive

# Path to the zip file in your Google Drive
zip_file_path = '/content/drive/MyDrive/validation_dataset.zip'

# Extract path (where you want to extract the contents)
extract_path = '/content'

# Create the extraction directory if it doesn't exist
os.makedirs(extract_path, exist_ok=True)

# Extract the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# Define the paths for the training and validation data
train_path = '/content/train_dataset'
val_path = '/content/validation_dataset'
test_path = '/content/test_dataset'

"""# **CNN**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from tensorflow.keras.metrics import Precision, Recall
import os

# Define the paths for the training and validation data
train_path = '/content/train_dataset'
val_path = '/content/validation_dataset'

batch_size = 64

# Create ImageDataGenerators for training and validation data
train_datagen = ImageDataGenerator(rescale=1./255, fill_mode='constant', cval=255)

val_datagen = ImageDataGenerator(rescale=1./255)  # Only rescale for validation data

test_datagen = ImageDataGenerator(rescale=1./255)  # Rescale only for test data

train_gen = train_datagen.flow_from_directory(train_path, target_size=(150,150),
                    class_mode='categorical', batch_size=batch_size)

val_gen = val_datagen.flow_from_directory(val_path, target_size=(150,150),
                class_mode='categorical', batch_size=batch_size)

test_gen = test_datagen.flow_from_directory(test_path, target_size=(150, 150),
                                            class_mode='categorical', batch_size=batch_size)


model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(150, 150, 3), padding='same'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Conv2D(128, (3,3), activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Conv2D(256, (3,3), activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Conv2D(512, (3,3), activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(1024, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(10, activation='softmax')
])

# Compiling the model with additional metrics
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy', Precision(name='precision'), Recall(name='recall')])

model.summary()

# Define callbacks
reduce_lr = ReduceLROnPlateau(factor=0.1, patience=5, min_lr=0.00001, verbose=1)
early_stop = EarlyStopping(patience=10, restore_best_weights=True, verbose=1)

# Train the model using the categorical labels
history = model.fit(train_gen, epochs=10, validation_data=val_gen, callbacks=[reduce_lr, early_stop])

# Evaluate the model on the validation set
val_loss, val_accuracy, val_precision, val_recall = model.evaluate(val_gen)

print(f'Validation Loss: {val_loss:.4f}')
print(f'Validation Accuracy: {val_accuracy:.4f}')
print(f'Validation Precision: {val_precision:.4f}')
print(f'Validation Recall: {val_recall:.4f}')

test_gen = test_datagen.flow_from_directory(
    test_path,
    target_size=(150, 150),
    class_mode='categorical',
    batch_size=batch_size)


evaluation_results = model.evaluate(test_gen, steps=test_gen.samples // batch_size)

print('Test Loss:', evaluation_results[0])
print('Test Accuracy:', evaluation_results[1])
print('Test Precision:', evaluation_results[2])
print('Test Recall:', evaluation_results[3])

val_gen = val_datagen.flow_from_directory(
    val_path,
    target_size=(150,150),
    class_mode='categorical',
    batch_size=batch_size)

evaluation_results = model.evaluate(val_gen, steps=val_gen.samples // batch_size)

print('Validaion Loss:', evaluation_results[0])
print('Validaion Accuracy:', evaluation_results[1])
print('Validaion Precision:', evaluation_results[2])
print('Validaion Recall:', evaluation_results[3])

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt

def plot_training_history(history):
    # Setup figure and axes
    plt.figure(figsize=(12, 6))

    # Subplot for accuracy
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.title('Model Accuracy')
    plt.ylabel('Accuracy')
    plt.xlabel('Epoch')
    plt.legend(loc='upper left')

    # Subplot for loss
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.title('Model Loss')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(loc='upper left')

    plt.tight_layout()
    plt.show()

# Assuming 'history' is defined and contains the history of a fitting model
plot_training_history(history)